### ISSUE TITLE
Documentation/Debugger Missing

### ISSUE THREAD

**Issue by calclover2514** [PeterTillema/ICE#108]
I cannot find the newest documentation/commands list anywhere. The link in the repo appears to be dead, and I don't have any of the newest commands in the list.
Also, when I tell ICE to debug a program, it tells me that the debugger is missing and to find it here: [www.tiny.cc/clibs](http://www.tiny.cc/clibs). Problem: It's not there.
I also started another issue here #94 that still hasn't been fixed.
I think that this is because the version of ICE that I have is outdated again.
If this is still a problem, please tell me, or if it is fixed, please send me the newest compiled version of ICE.
Thanks

**Comment by PeterTillema** [comment]
https://github.com/PeterTillema/ICEDebugger
https://github.com/PeterTillema/ICE/blob/master/documentation/commands.html
If that issue still isn't solved, reopen it, then I can try and eventually fix things. It says to go to http://tiny.cc/clibs because that's where the other libraries are present, and I have no way to change the error message (currently).

**Comment by calclover2514** [comment]
OK Thank You
