### ISSUE TITLE
Memory error on start up.

### ISSUE THREAD

**Issue by DestroyerMCE** [PeterTillema/ICE#155]
I start ICE to compile a program and it just says: ERROR: MEMORY. I have 42591 free for ram, and 317753 for Archive. This just happened and it was fine before

**Comment by TheLastMillennial** [comment]
This isn't an ICE issue, you simply don't have enough RAM. Press [2nd]>[+]>[2]>[1] and press [enter] on any program or appvar that doesn't have a * next to it. The * means it's in the Archive, otherwise it's in the RAM. 

You shouldn't be storing things in RAM because they'll get lost if the calculator resets. When you store all your programs and appvars in Archive, you should end up with at least 140,000 bytes of free RAM which is plenty to run any program.
