### ISSUE TITLE
For( with a negative increment

### ISSUE THREAD

**Issue by Ti64CLi** [PeterTillema/ICE#66]
I found a bug. If I do For(VAR,BEG,END,-1 such as For(VAR,10,0,-1, then I compile it, with this code for example:
```
For(VAR,10,0,-1
Disp VAR,i
Pause
End
```
It displays 10 to 0, then -1, -2 etc
It seems it can't stop at 0 :(
Would you fix that?
Thank you in advance
Ti64CLi++

**Comment by PeterTillema** [comment]
Can confirm:
https://github.com/PeterTillema/ICE/blob/ebd3cb7289ca25c37d22884df41fb3da0a058d04/src/parse.c#L1483-L1489

**Comment by PeterTillema** [comment]
Actually, this makes sense, because it basically compares `VAR` with 0, using the code `If VAR>=0` which is, of course, always true since `VAR` is always positive. I can fix it, but then `0->VARB : For(VAR,10,VARB,~1` wouldn't work. I will just leave it as it is, because ICE doesn't use signed comparisons (i.e. using 'negatives'). Sorry, you need to find a work-around @Ti64CLi  :(

**Comment by Ti64CLi** [comment]
Sorry to answer so late.
No problem, thanks for your answer

2018-06-11 19:07 GMT+02:00 Peter Tillema <notifications@github.com>:
